### ISSUE TITLE
Use Liberapay for funding

### ISSUE THREAD

**Issue by davidak** [opencompany/www.opencompany.org#175] opened 2018-04-11 07:01 UTC
The Website says

>The Initiative is funded on Gratipay

but that shut down in 2017.

I suggest using the advertised fork, liberapay!

https://gratipay.com/
https://en.liberapay.com/

I tested Liberapay and was able to add money to my wallet, donate and withdraw money.

**Comment by waldyrious** [comment] 2018-07-05 00:37
The idea is excellent, but not really actionable at the moment IMO. The main issue is that this project doesn't seem to have any active maintainers. I'm not sure what gain we'd have in accepting donations (and recurring ones especially), when there's no ongoing work that would justify them. @tenkabuto, @galuszkak and I tried to keep it alive following #166, but ran out of steam soon after -- an unfortunately common occurrence in this sort of projects.

In my case, the issue is not money, but time/headspace (unless by some miracle we managed to afford pay for a full-time position, as my current professional situation doesn't allow a gradual shift in time dedication that would allow a scalable growth in community-supported financing for this project). I'd be curious to hear what @tenkabuto and @galuszkak think (and also @balupton who [joined recently](https://github.com/opencompany/www.opencompany.org/issues/176#issuecomment-397586587) in the wake of #176, as well as @timothyfcook, @chadwhitacre, and others who may wish to voice their thoughts.)

**Comment by balupton** [comment] 2018-07-05 15:19
Liberapay, Patreon, Open Collective are the new options for receiving funds.

Although, currently there seems no need for any funds.

That Gratipay text should still be updated though if it is there.

**Comment by waldyrious** [comment] 2018-11-12 18:57
I actually forgot a detail in my previous comment: I've been paying for the the opencompany.org domain out of my pocket, so that could be an expense worth funding through Liberapay or any similar method.

For the time being, I created a [team at Liberapay](https://liberapay.com/opencompany/), and invited @balupton. I didn't find accounts for any of the other [owners of the organization](https://github.com/orgs/opencompany/people?query=+role%3Aowner) (@tenkabuto, @galuszkak @timothyfcook), nor for @chadwhitacre, so please do create accounts there and let me know the username so I can invite you to the team.

If you prefer setting this up elsewhere, let me know.

As for the domain, I'll renew the registration out of my pocket again, and will collect the corresponding amount back once the Liberapay gets sufficient funds.

**Comment by waldyrious** [comment] 2018-12-11 09:45
Oh wow. Now that's quite a bit of responsibility. I hope the rest of you guys sign up to share it :)

**Comment by nobodxbodon** [comment] 2018-12-11 21:09
@waldyrious thanks for the invite. I'm glad to help setup accounting at least, which I helped back for https://github.com/gratipay/finances/pull/35, as IMO public accurate book keeping from the start is ideal. And hi @chadwhitacre it's been a while.

**Comment by waldyrious** [comment] 2018-12-11 23:46
@nobodxbodon great to hear that. Let me know what's your Liberapay handle so I can add you to the team there.

**Comment by nobodxbodon** [comment] 2018-12-12 00:38
@waldyrious I just created account "nobodxbodon", the same as my github account id. I don't plan to take any money until I make substantial contribution to the project **and** understand how to report the income.
I'd look forward to your vision going forward, because in my view it'll be more and more challenging and critical to stay open and be more connected for all the open companies.

**Comment by balupton** [comment] 2018-12-12 12:43
If no one from open company wants the funds, perhaps we should direct the funds between open companies instead — At @bevry we have a lot of projects we want to do, but no funding — probably others on the open company listing that are the same.

**Comment by nobodxbodon** [comment] 2018-12-12 15:17
@balupton 
> find a way to use that money to revitalise the open company initiative.

+1

@waldyrious shall we open a new issue about this?

**Comment by waldyrious** [comment] 2018-12-12 22:18
@nobodxbodon, great, thanks. I've invited you to the Liberapay team.

I think we can close this issue for the time being. Happy to add more people later on.

I don't have any plans for how to use the Liberapay funds, other than paying for the domain registration (my current take on Liberapay amounts to exactly that value). But let's discuss further in #177.

**Comment by MathiasRenner** [comment] 2019-08-27 13:10
I updated all the website from Gratipay (not even existing any more) to Liberapay:
https://github.com/opencompany/www.opencompany.org/pull/179

I found your project on Liberapay, found it interesting and thought I invest some time to help a bit.

**Comment by waldyrious** [comment] 2020-01-15 16:08
> I think we can close this issue for the time being.

Since there was no objection to this, I'll close the issue. The Liberapay setup has been completed: our page is up at https://liberapay.com/opencompany, and members can be added according to my comment [above](https://github.com/opencompany/www.opencompany.org/issues/175#issuecomment-437991800).

**Closed by waldyrious** 2020-01-15 16:08 UTC
